name: Deploy

on:
  push:
    tags:
      - "Release_launch4j-*_*"

jobs:
  variables:
    outputs:
      compile_version: ${{ steps.get-compile-version.outputs.compile_version }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"
          cache: maven
          server-id: github

      - name: convert to maven
        id: convert_maven
        run: ant switch-to-maven

      - name: get compile version
        id: get-compile-version
        run: echo 'compile_version='"$(mvn help:evaluate -Dexpression=maven.compiler.source -q -DforceStdout)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: variables
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{needs.variables.outputs.compile_version}}
          distribution: "adopt"
          cache: maven
          server-id: github
      
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: convert to maven
        id: convert_maven
        run: ant switch-to-maven
          
      - name: Publish to GitHub Packages Apache Maven
        run: |
          mvn -B -P full-release deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}