name: Deploy to GitHub Packages Maven

on:
  push:
    tags:
      - "Release_launch4j-*_*"

jobs:
  compiler_version:
    uses: neum-eng/.github-private/.github/workflows/java-version.yml@master
    with: 
      mvn-args: "-f maven -o"

  deploy:
    needs: compiler_version
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{needs.compiler_version.outputs.version}}
          distribution: "adopt"
          cache: maven
      - name: convert to maven
        id: convert_maven
        run: ant switch-to-maven
      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B -P full-release deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}